@echo off
type screen\background\b1
type screen\background\b2
type screen\background\b3
type screen\background\b4
type screen\background\b5
type screen\background\b6
type screen\background\b7
type screen\background\b8
type screen\background\b9
type screen\background\b10
type screen\background\b11
type screen\background\b12
type screen\background\b13
type screen\background\b14
type screen\background\b15
type screen\background\b16
type screen\background\b17
type screen\background\b18
type screen\background\b19
type screen\background\b20
type screen\background\b21
type screen\background\b22
type screen\background\b23
@echo on